language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "jasM2lInHDlaJyAzVySTp+KWKYOrqjtdmuisOQjiLFxSN2pxMknNDoIn+mjYfAz73Ft3fga3dxXGVWA1GFQxeRrL6tQGJ9EtiNffLEC9qxLMUlx7UuWnkey1vu59SFeQxy/Z9OnUrqhnbp8kJcbZKgeyTj7fiRnZ9AL2QOIvTorCdLcmc1rupRumoTw3fJT7EjM3o1/pNvW2m/FELJYtbyGQhfYpTCyUrQuw66Ow7wuU3kTaw/U8ziZB7eFGlkYVuq3G3+YOEt54Vh0AADsd2olducNQMBObe91CqtVRQoz5Rs6xsotwKlnLwaHx20w8MpvPFIhs3MKAmKQQLIDUFUA7sFH8tktVGOPCRTUY7kYdDlmXYi8qeKapeNUwd2qpDMWaqa/mr6N8KsFWRggi47ittijnUI/YqDImjm0WVUL8ytMtvv48/5TsBE8+DIwVbFXmFiib5GDRz6JCdGdOyt+nCp6Qa0/2xcIWZ/m/1cuSzQs0pycqIePsJJXYXbO196cWYVsa4L4ridnnzVJoA7jGSzNGUUTEhI64lMfUB9rrR4HBJW3VcSJ7D7GdRyzjYffCGd/Cl+bMVeLq6R9Ku3VqZzok7NaN+7q+B9WiUAdwXl6gRyndhbTEAjDWZqisu/dELkHW515zk/MJNEe1QNtQAxvP+yNOyjtUY6NKPHg="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "cm8dWTGAcWang2LkHzznipiEnz2V3mWOSjuHHNPWZe3geU5xmYfPZhdlZGy9SHCNTASRxS/EcEwdTAYJPVEP8I61Cd45XzTCJ2MbuFKkfytkcHxo32FO4BN04gbsWn/T/1IG0mRjiuSJhZTCAJvDYfhtoaUFxbcz+/QYVkyFb4jydRAmFnIg+7BepoGk58ZW1AKG7hVwUyHoH0evikLaW6kNwKL5Xpw5qrgvJTiYJ65BKefF3uaSBemIbLn6K6OW0MmfHfLStiXjgA18CLPTNjSb3Bk+ICGI2guDWxowwqiJYoMIldlxDBTiUBG5tvDSsnyZYNCKFLGv4p8OvC/DfDH8Ms832vUnRNo5FN2HsbPtQAie3A5EFg2fovhRYlCmsgJ8zL5ft0qqm5olG9D1bZ1Neerma6+rrFBvOCOBxSwIi+Suyj4G8jeJVA9G46XSXiZ0hmiE/PGYmQFzZeS6OfQ3nD89MiN0gfiPVtu09rMXypsBzkkSEEHda2SB3FluI71M98yuqQ0uU0zDKrZZtyjYNdVm4e88Itu9arhv9J6H7WrrqDCasbU4sK5jzbIY2qQTY+7Wgb+fjNBnhnNRKFqiP44MK2bWqw1IYWq4gAPuwrnIGI7Jpb760QLIcbYdQtmgFGHK6GVl0Ats8S4coaT6n6GrLSOFDeWPJMDwrPg="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "kXCUAtWBhWwwNPuGFPRZk53f9fXp7ezAQZvSMp67CfuWF7mRajINDSs17NrgQj41jGQELxZUD+9f6tRvXZJKkWMM0iCBmOEHjNuSG3NCs12vvW+1i9ZLhhoN+oqX/4Ex1Eq2aYuya1rYPNqsjick3xHJQDXJiAhta+GTc0YwYqeSfRGqwX3HLMXMA6AToH3k3ZHB9XzT3Gz0pbSUrgNS52vLNBcnWeqAcPlaObvYPZr6Hzx6VX4m47rbwpyd1iZZxzR1z7QxtV7seqtd/auUsVlPMKwDrmYFufjlKkhMUcNrbc0Cb5Xt4Vyt+pLQ0k4zTDuyg+OnencHQ8JijtZ8LCwtQU/PjihyGAjmimiCDxkSDQjw22PmqTDgwiNjwYqwsd3zVMeWslZM+a4TJ+3IVmcAGnnCULJJ1rjOBc/JzmUmyJ0TwwbhD5T9fGEaXxWi9vtu1yEHKAswYrnIUMd5oRL8hgHeRUfvwyeOpR4S0E1QkDBbc/I6dnaG4yrjxlgyVSw4scl1ACAoM+3VMgGBigUFaHfo5U7SJmg/l+5R/T/nM/QUc7Nil2TVFPsxyuxMrVYp0esNrbSIxocxMbRn7UomHYYtymtbQoHki31mFaUBBuFS4877oOqukUq6Dl6Dp2C9De6E7Nz5L5/0F5yasI7cuDvkjLdBSV2PbNLnaFY="
    - # ^^ GPG_KEY_NAME
    - secure: "FfFhGcu2ZbmF+IYy6sfpdUN/7GsyYQ2hST+s1LrzpM+tvxVShsk8A9vcLnLwXGbyQEAPV7qUjKzXbbJpdNxs+UWZ3mejTX9LhZFLZjVP6yZIIc76weGHmTcJFkycox0YEcGKWvAx9nLrGn4uC85A6bfteJmmJ9GRZgs8PIXxewn3KcuqSslwcTMVe+lVOD/qMScjnqjzliEFWAsg2HLyimHado9nGS+LBOEZ98Pc4V7uwsg2WoSIpxobYJvKuErRrKWVjqXUcSx0gsrSjvlPmNlkb3SAZ8Kn1cyIV3mPFSZmq4MDbwYzXfH62cAZXHfIbADGlmWICWA3tMbSReK8COBZb3Jo8AXRSjXLHnCJaBC3nQ56wMdy8kNLYbafzjPqZjkDi5ciRPJ+PTQALsCQqwlP1AcYlTLLhEPIIZtYSBz1jG6H0fFHBhOQhGL4f0U5IHwgmlSaIThO4HheD9t5Co1wqUr3WwqbnRDtrdPpDofacrjtxMBpPBk/2gk8YJmMibV4b68kMDzaaeQJMH2Sp796WaSFrlLLUb4LJGmS91I4D3Cv1KFnO+ZXbKIM1rsQEIrgIxLQPWewr1LKk7wdoAgvchzNX7IGvNljNGC812mwYPAUvA9ncDJepniDz68x66Xj+oLt0lgImwW5iRPpED7Wo47R+vPfjYsSxL/sC78="
    - # ^^ GPG_PASSPHRASE

sudo: required
services:
  - docker

before_install:
  - ./mvnw install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw -B -P !build-extras test

deploy:
  sudo: false
  services: []
  provider: script
  script: release/deploy.sh
  on:
    tags: true
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
